import { v4 as uuidv4 } from "uuid";

const issuesCategories = [
  {
    id: uuidv4(),
    category: "Grid Zero Feed In Failure",
    subIssues: [
      "Cellular Network Week",
      "LAN Switched Off",
      "LAN Wire Breakage",
      "Wattmon Adaptor Failure",
      "Wattmon Adaptor Removed from Socket",
      "Wattmon SD Card Failure",
      "Wattmon Worng Configuration During Update",
    ],
  },
  {
    id: uuidv4(),
    category: "Human Error",
    subIssues: [
      "Unauthorized shutdown",
      "Forgot to Switch ON breaker after Maintenance",
      "Loose connection during maintenance",
    ],
  },
  {
    id: uuidv4(),
    category: "HV Panel Issue",
    subIssues: [
      "Breaker trip",
      "Panel overheating",
      "Relay malfunction",
      "CT Issue",
      "PT Issue",
      "Surge Arrestor Issue",
      "Burn/Blast",
    ],
  },
  {
    id: uuidv4(),
    category: "Inverter Issues",
    subIssues: [
      "Inverter Offline",
      "Inverter Not Generating",
      "MPPT Failure",
      "DC Bus Overvoltage",
      "Grid Overvoltage / Undervoltage",
      "Grid Frequency Out of Range",
      "Phase Loss or Imbalance",
      "Ground Fault Detected",
      "IGBT Failure",
      "Internal Relay Fault",
      "EEPROM Failure",
      "Control Board Malfunction",
      "Inverter Overtemperature",
      "Fan Failure or Fan Blocked",
      "Inverter Derating Due to High Temp",
      "Reverse Polarity Detected",
      "DC String Disconnected",
      "AC Output Overcurrent",
      "Residual Current Device (RCD) Tripped",
      "Communication Loss with Logger/Portal",
      "RS485/WiFi/Ethernet Connection Failure",
      "Frequent Reboots / Restart Loop",
      "Self-Test Failure",
      "Firmware Error or Mismatch",
      "Internal Error (Code e.g., E021, F07, etc.)",
      "Inverter Display Blank",
      "Grid Connection Timeout",
      "Inverter Stuck in Initialization",
    ],
  },
  {
    id: uuidv4(),
    category: "MCB/MCCB Issues",
    subIssues: [
      "MCB tripped",
      "MCB burnt",
      "Loose MCB terminals",
      "MCCB tripped",
      "MCCB burnt",
      "Loose MCCB terminals",
    ],
  },
  {
    id: uuidv4(),
    category: "Module Failure",
    subIssues: [
      "Hotspot",
      "Broken glass",
      "Snail trail",
      "Modules Degraded",
      "Junction Box Issue",
      "Backsheet Issue",
    ],
  },
  {
    id: uuidv4(),
    category: "Natural Disaster",
    subIssues: ["Lightning strike", "Heavy rain", "Wind damage"],
  },
  {
    id: uuidv4(),
    category: "Net Metering",
    subIssues: [
      "CEIG Inspection in process",
      "Netmeter Installation in process",
      "Net meter sync error",
    ],
  },
  {
    id: uuidv4(),
    category: "Preventive Maintenance",
    subIssues: ["Monthly checkup", "Tightening terminals", "Visual inspection"],
  },
  {
    id: uuidv4(),
    category: "PV Module Overtemperature",
    subIssues: ["Above 75°C", "Localized heating", "Dust accumulation"],
  },
  {
    id: uuidv4(),
    category: "Shadow",
    subIssues: ["Tree shade", "Building shade", "Bird nest"],
  },
  {
    id: uuidv4(),
    category: "Sticky Dust Issue",
    subIssues: ["Cement dust", "Adhesive residue", "Bird droppings"],
  },
  {
    id: uuidv4(),
    category: "TL",
    subIssues: [
      "Energy Meter PT-MCB trip",
      "Inverter Communication issue",
      "Meter Communication issue",
    ],
  },
  {
    id: uuidv4(),
    category: "Transformer Issue",
    subIssues: [
      "Transformer Oil Leakage",
      "Buchholz Relay Tripped",
      "High Transformer Temperature",
      "Oil Temperature High Alarm",
      "Winding Temperature High",
      "Overload Trip",
      "HV or LV Side Fuse Blown",
      "Low Oil Level",
      "Low Insulation Resistance (IR)",
      "Earthing Fault at Transformer",
      "Abnormal Humming Noise",
      "No Output Voltage",
      "LV/HT Terminal Loose or Burnt",
      "Neutral Disconnected",
      "LT Cable Overheating",
      "HV Breaker Tripping due to Transformer Fault",
      "Surge Arrestor Failure",
      "OLTC Malfunction (for tap-changing transformers)",
      "Corroded or Loose Busbar Connections",
      "Moisture or Water Ingress Detected",
      "Bushing Flashover or Damage",
      "Vibration Detected at Base or Core",
      "Transformer Not Picking Load",
      "External Short Circuit on Output",
      "Phase-to-Phase Short Inside Transformer",
    ],
  },
  {
    id: uuidv4(),
    category: "Wattmon Failure",
    subIssues: [
      "No communication",
      "Data mismatch",
      "SD Card Failure",
      "Device Failure",
    ],
  },
  {
    id: uuidv4(),
    category: "AC Cable Puncture",
    subIssues: [
      "Cable damaged during work",
      "Rodent damage",
      "Insulation breakdown",
    ],
  },
  {
    id: uuidv4(),
    category: "Cleaning",
    subIssues: [
      "Panel not cleaned due to vendor manpower issue",
      "Improper cleaning",
      "Water stains",
      "Client not given permisison for cleaning",
    ],
  },
  {
    id: uuidv4(),
    category: "Communication Issue",
    subIssues: [
      "No data to portal",
      "LAN cable cut",
      "WLAN not connected",
      "Cellular Network Issue",
    ],
  },
  {
    id: uuidv4(),
    category: "Customer Related Issue",
    subIssues: [
      "Customer-Initiated Shutdown",
      "Restricted Site Access (No Entry for O&M Team)",
      "Shutdown for Customer Electrical Maintenance",
      "Load Transfer Activity (Client Grid Load Change)",
      "DG Synchronization Activity by Customer",
      "Customer-Requested Isolation of Plant",
      "Deemed Generation Condition (Plant Okay but Export Restricted)",
      "Fire Drill or Emergency Mock Activity at Site",
      "Customer Not Willing for Preventive Maintenance Today",
      "Manual Shutdown by Customer Electrician",
      "Holiday / Factory Closure / Sunday Shutdown",
      "Miscommunication between Client and O&M",
      "Client Safety Protocol Blocking Access",
      "Plant Access Delayed Due to Gate Pass / ID Issues",
      "Customer Load Side Breaker Turned Off",
      "Main Panel or Transformer Locked by Client",
      "Plant Shutdown Due to No Net Metering Consent from Customer",
      "Customer Disconnected SCADA/Internet",
      "Customer Refuses Inverter Restart after Fault",
      "Export Restriction Imposed by Client",
      "Manually shutdown due to client side payment issue",
    ],
  },

  {
    id: uuidv4(),
    category: "DC Cable Puncture",
    subIssues: ["PV wire cut", "Connector pulled out", "Short in combiner"],
  },
  {
    id: uuidv4(),
    category: "DC Isolation",
    subIssues: ["DC switch turned off", "Fuse blown", "Combiner box isolation"],
  },
  {
    id: uuidv4(),
    category: "DG Protection Active",
  },
  {
    id: uuidv4(),
    category: "DG Protection Failure",
    subIssues: [
      "Cellular Network Week",
      "LAN Switched Off",
      "LAN Wire Breakage",
      "Wattmon Adaptor Failure",
      "Wattmon Adaptor Removed from Socket",
      "Wattmon SD Card Failure",
      "Wattmon Worng Configuration During Update",
    ],
  },
  {
    id: uuidv4(),
    category: "Fuse, TB and MC4",
    subIssues: [
      "Blown fuse",
      "Loose terminal block",
      "MC4 heating",
      "TB failure",
    ],
  },
  {
    id: uuidv4(),
    category: "Grid Failure",
    subIssues: ["No grid supply", "Grid under voltage", "Phase failure"],
  },
  {
    id: uuidv4(),
    category: "Grid Quality",
    subIssues: ["Voltage fluctuation", "Frequency variation", "THD high"],
  },
  {
    id: uuidv4(),
    category: "Grid Zero Feed In Active",
    subIssues: [
      "Zero export mode",
      "Manual relay activation",
      "Timer-based logic",
    ],
  },
];

const typeOfLoss = [
  {
    id: uuidv4(),
    controllability: "UnControllable",
  },
  {
    id: uuidv4(),
    controllability: "Controllable",
  },
];

export { issuesCategories, typeOfLoss };
